# Generated by Django 5.0.7 on 2024-09-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
